name: hoops
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.15.1 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.1
  flutter_svg:
  pinput: 1.2.2
  get_storage:
  firebase_auth: ^3.3.18
  firebase_core: ^1.17.0
  kiwi:
  animated_bottom_navigation_bar:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^1.0.0
  lints: 1.0.1
  build_runner:
  kiwi_generator:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/